//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_bill_tbl
    {
        public int ID { get; set; }
        public string AssetName { get; set; }
        public string AssetImage { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> AssetAmount { get; set; }
        public Nullable<System.DateTime> AssetDate { get; set; }
    }
}
