//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_history
    {
        public long id { get; set; }
        public long booking_id { get; set; }
        public System.DateTime booking_start_date { get; set; }
        public System.DateTime booking_end_date { get; set; }
    }
}
