//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUT_Updates
    {
        public int ID { get; set; }
        public string News { get; set; }
        public string Updates { get; set; }
        public string Tournaments { get; set; }
    }
}
