//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricelst
    {
        public int ID { get; set; }
        public Nullable<decimal> mem3m { get; set; }
        public Nullable<decimal> mem6m { get; set; }
        public Nullable<decimal> singlem { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> adultcoaching { get; set; }
        public Nullable<decimal> childcoaching { get; set; }
    }
}
