//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }
        public Nullable<decimal> CreditTotal { get; set; }
        public Nullable<decimal> CreditUsed { get; set; }
        public long BookingID { get; set; }
        public string MemberID { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual Wallet Wallet1 { get; set; }
        public virtual Wallet Wallet2 { get; set; }
    }
}
